### ISSUE TITLE
bug: Demonware services may process an unexpected number of bytes when reading a ticket

### ISSUE THREAD

**Issue by imatiramisu** [momo5502/open-iw5#105]
## Problem

In the code below, the first argument to `std::min` is an uninitialized variable.
- If the value of `ticket_size` is less than `1024`, then the ticket will be read incorrectly.
   - This will likely lead to an access violation error in the proceeding code.

## Mitigation

I'm not too familiar with the networking model, however, it seems like the options are:
- Read the ticket size from the buffer if that's part of the communication model.
- Pick an arbitrary size for the ticket to maintain correctness.

## Relevant Code
https://github.com/momo5502/open-iw5/blob/d36452a939d1ebc9d86054732182e79fa4dca172/src/game/demonware/services/bdDediAuth.cpp#L18-L23

https://github.com/momo5502/open-iw5/blob/d36452a939d1ebc9d86054732182e79fa4dca172/src/game/demonware/services/bdDediRSAAuth.cpp#L18-L26

**Comment by momo5502** [comment]
Good issue, however there is no dedi support. This means the dedi authentication code is unused. So it would need fixes anyways.

**Comment by momo5502** [comment]
I have not planned to implement dedi support to this project, as I'm not actively working on it, which means in consequence this code is never going to be used, so I won't bother fixing this or changing this code in any way. If someone is willing to create a PR, I will merge it, otherwise I'm just gonna close this issue.
