### ISSUE TITLE
SP mod support?

### ISSUE THREAD

**Issue by SadSlothXL** [momo5502/open-iw5#268]
Will sp mod support be added to this project? Would love to mod sp and co-op!

**Comment by diamante0018** [comment]
Hi, since this project was released you could have always loaded custom scripts on both MP or SP so not sure where you are getting at. Follow the cod4x intro to GSC guide to load GSC scripts. that is a good guide.
There is no co-op, if you want to play co-op you will have to buy the game on Steam and play with your friends there.
This should answer all of your questions.
Also, this project does not currently accept feature requests, but thanks for your interest.

**Comment by SadSlothXL** [comment]
was mainly asking if being able to use custom fastfiles for sp and co-op would be coming, that type of modding and for co-op be able to play with other ppl doesn't bother me (but would be cool), I just want to mod the mission and survival. :)

**Comment by diamante0018** [comment]
Sorry, that feature is not a thing and will most likely never be done.
You can only mod with GSC scripts ( previously chai scripts )
